-- Auto-generated from schema-map-postgres.yaml (map@sha1:6D9B52237D942B2B3855FD0F5500331B935A7C62)
-- engine: postgres
-- table:  kms_routing_policies

CREATE TABLE IF NOT EXISTS kms_routing_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  priority INTEGER NOT NULL DEFAULT 0,
  strategy TEXT NOT NULL DEFAULT 'prefer',      -- 'prefer','require','avoid'
  match JSONB NULL,                             -- e.g. {"tenant_id":123,"region":"eu"}
  providers JSONB NOT NULL,                     -- e.g. [{"provider_id":1,"weight":80},...]
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_kms_route_strategy CHECK (strategy IN ('prefer','require','avoid'))
);
